#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 12 13:10:32 2024

@author: duanzhang
"""
##this file matches state and county name in 1990s file with fips codes

import pandas as pd
import os
df = pd.read_excel(os.path.join(os.path.dirname(__file__), r"clean_extractdata_1990s.xlsx"),
                   dtype={'file':'string','state':'string','geography':'string','tract':'string'})
#%%
df1990 = df[df['file']=="1990"]
df1996 = df[df['file']=="1996"]
df1999 = df[(df['file']=="1999a") | (df['file']=="1999b")]
df2000 = df[df['file']=="2000"]
def f(row):
    if pd.notna(row['state2']):
        val = row['state2']
    elif pd.notna(row['state3']):
        val = row['state3']
    else:
        val = row['state1']
    return val
#%%
#match 1990 with fips
df1990[['state1','state2']] = df1990['state'].str.split(', ',n=1, expand=True)
df1990[['state1','state3']] = df1990['state'].str.split('.',n=1, expand=True)
df1990['state3'] = df1990['state3'].str.strip()
#%%
df1990['state only'] = df1990[['state1','state2','state3']].apply(f, axis=1)

import addfips
af = addfips.AddFIPS()
df1990 = df1990.reset_index()
cfips1990 = []
for idx,row in df1990.iterrows():
    cfips1990.append(af.get_county_fips(row['geograoy'], row['state only']))
df1990['county_fips'] = cfips1990

#%%
#match 1996
df1996[['state1','state2']] = df1996['state'].str.split(', ',n=1, expand=True)
df1996[['state1','state3']] = df1996['state'].str.split('.',n=1, expand=True)
df1996['state3'] = df1996['state3'].str.strip()
df1996['state only'] = df1996[['state1','state2','state3']].apply(f, axis=1)
df1996 = df1996.reset_index()
cfips1996 = []
for idx,row in df1996.iterrows():
    cfips1996.append(af.get_county_fips(row['geograoy'], row['state only']))
df1996['county_fips'] = cfips1996

#%%
#match 1999 fips
def f2(row):
    if pd.notna(row['state2']):
        val = row['state2']
    else:
        val = row['state1']
    return val
df1999[['state1','state2']] = df1999['state'].str.split(', ',n=1, expand=True)
df1999['state only'] = df1999[['state1','state2']].apply(f2, axis=1)
df1999 = df1999.reset_index()
cfips1999 = []
for idx,row in df1999.iterrows():
    cfips1999.append(af.get_county_fips(row['geograoy'], row['state only']))
df1999['county_fips'] = cfips1999
#%%
#match 2000 fips
df2000[['state1','state2']] = df2000['state'].str.split(', ',n=1, expand=True)
df2000['state only'] = df2000[['state1','state2']].apply(f2, axis=1)
df2000 = df2000.reset_index()
cfips2000 = []
for idx,row in df2000.iterrows():
    cfips2000.append(af.get_county_fips(row['geograoy'], row['state only']))
df2000['county_fips'] = cfips2000

#%%
df1990.to_excel('1990withFips.xlsx')
df1996.to_excel('1996withFips.xlsx')
df1999.to_excel('1999withFips.xlsx')
df2000.to_excel('2000withFips.xlsx')
